// /robots.txt — GENERATED, from the SAME single source as the <head> robots meta.
//
// WHY THIS REPLACED public/robots.txt: the static file said "Disallow: /"
// forever. Flipping site.published to true changed the meta tag in Base.astro
// and changed nothing here, so a published site would have shipped an
// indexable <head> behind a robots.txt that still blocked every crawler — two
// switches for one decision, and the second one silently wrong. Now
// src/content/data/site.json "published" is the only input, read by exactly
// three consumers: this route, src/layouts/Base.astro, and
// scripts/check-publish.mjs.
//
// WHY AN ASTRO ROUTE AND NOT A BUILD SCRIPT: a route is in the same module
// graph as the page that renders the meta tag, so both flip in the same build
// with no ordering to get wrong, it works identically under `npm run build`,
// `npm run build:draft` and `astro dev`, and there is no extra script anyone
// can forget to call. public/robots.txt was deleted in the same commit — a
// file in public/ is copied verbatim over routes of the same name, so leaving
// it would have silently beaten this route.
//
// NOTE: no `Sitemap:` line. @astrojs/sitemap is currently DISABLED in
// astro.config.mjs (it crashes on this build), so no sitemap-index.xml is
// emitted; advertising one would point crawlers at a 404. Re-enable the
// integration and add the line back here in the same change.
import type { APIRoute } from 'astro';
import site from '../content/data/site.json';

const BLOCKED = `# ZAYA — NOT cleared for indexing (site.json published: false).
# F4 BINDING carve-out: no crawler until real Privacy + Terms and real content
# exist. Generated by src/pages/robots.txt.ts from the same flag as the
# <head> robots meta — there is no second switch to forget.
User-agent: *
Disallow: /
`;

const ALLOWED = `# ZAYA — cleared for indexing (site.json published: true).
# Generated by src/pages/robots.txt.ts from the same flag as the <head> robots
# meta. Re-add a Sitemap: line here when @astrojs/sitemap is re-enabled in
# astro.config.mjs (it is disabled today, so there is no sitemap to advertise).
User-agent: *
Allow: /
`;

export const GET: APIRoute = () =>
  new Response(site.published === true ? ALLOWED : BLOCKED, {
    headers: { 'content-type': 'text/plain; charset=utf-8' },
  });
